#!/bin/bash

ANSWER=""
while [ "$ANSWER" != "yes" ] && [ "$ANSWER" != "no" ]; do
    echo -n "Do you want to update the system? [yes/no]"
    read ANSWER
done

if [ "$ANSWER" = "yes" ]; then
    sudo apt-get update -y && sudo apt-get upgrade -y && sudo apt-get dist-upgrade -y && sudo apt-get autoremove -y && sudo apt-get autoclean -y
fi
